version: '2'
services:

  worker:
    build: worker
    depends_on:
      - consul
    
  consul:
    build: consul

  haproxy:
    build: haproxy
    depends_on:
      - consul
      - worker
  
  haproxy_backup:
    build: haproxy_backup
    depends_on:
      - consul
      - worker

  haproxy_front:
    build: haproxy_front
    depends_on:
      - consul
      - worker
      - haproxy
      - haproxy_backup
    ports:
      - "80:80"
